---
kind: template
load: docker-build-multiarch.yaml
data:
  dockerfiledir: .
  hubimagename: tldr-webui
  repotype: hub
  imagetag: latest  
  branches: ['master', 'main']
  buildarch: linux/arm64/v8,linux/amd64
